### ISSUE TITLE
Warnings with Elixir 1.5.2 and version 1.1.1

### ISSUE THREAD

**Issue by quatermain** [nhu313/Quinn#11]
Hello,

I got couple of warnings with Elixir 1.5.2 and version 1.1.1:
```
warning: String.strip/1 is deprecated, use String.trim/1
  lib/xml_parser/xml_parser.ex:27

warning: String.strip/1 is deprecated, use String.trim/1
  lib/xml_parser/xml_parser.ex:37

```

**Comment by nhu313** [comment]
Oh I didn't know that is a thing. I haven't written Elixir in awhile. Thanks for letting me know @quatermain. I'll get it fix this weekend. I'm currently swamped at work :(
